### ISSUE TITLE
Corrections

### ISSUE THREAD

**Issue by Pomilui** [Pomilui/Akira_Page#10]
@ebeshero @quantum-satire @MarkTheShark01 

Hey, all.  I've started to make corrections (including the incorrectly spelled "colonel") to the AkiraODD and AkiraTEI.   However, when I'm making changes to both, I'm still getting an error "value of attribute "who" is invalid. It must be equal to... #akirafan... and the rest in AkiraTEI.xml.  When I'm adding missing characters or changing the spelling of some in the valList in AkiraODD and the particDesc in AkiraTEI, should I be using the wrench to be able to use remove the errors in the AkiraTEI?   

   Thanks.

  - Nick

**Comment by ebeshero** [comment]
@Pomilui Yes--you'll need to "run the wrench" in oXygen to re-generate the Relax-NG schema so it'll run your updated schema rules.

**Comment by Pomilui** [comment]
@ebeshero @quantum-satire @MarkTheShark01 

Update:  I'm down to 2 errors left, and they are both like this:   `<sp who="#council6 #council5" n="533" from="00:46:17.206" to="00:46:20.917" >
<l>- Take that "old man" comment back!
- Your lack of policy started this mess!</l>
</sp>`                        ....

  where the DVD subtitle software captured two lines from two different speakers (not being controlled by anyone else).  Should I create an new `<sp>` with n=533.5 and something like some estimate of "from...to"? 

   Thanks.

**Comment by ebeshero** [comment]
@Pomilui w00t! Congrats on cleaning up the new TEI-ified Akira script! Note: the `@from` and `@to` attributes are not required on `<sp>` elements--they're only optional (as I noticed that not all of your `<sp>` elements have time information associated with them. I'm glad to see this came back green for you! :-) Now, onwards to processing! You can put that up in the eXist-db and query away...and you can transform it, too.... I think we'll maybe use your fresh new script for the homework assignment coming up on Monday (due next Wed.)....
