### ISSUE TITLE
No permission to edit Index.html

### ISSUE THREAD

**Issue by Pomilui** [Pomilui/Akira_Page#14]
@quantum-satire @ebeshero 

  Hey, Ally.  I tried to update the index.html to correct the server side include problems we've been having, but I'm unable to edit it or update it since you're the owner.  I'll go ahead and push the updated files to the website folder.  Please let me know what needs to be done to update these files.  Thanks.

 - Nick

**Comment by quantum-satire** [comment]
@Pomilui What I've had to do in the past (at least for my project) was delete the old file in the server and then push the new one to replace it. Try that, and see if it works!

**Comment by Pomilui** [comment]
@quantum-satire  I'll try to delete it, but I may not have permission.  I'll try it later today.

**Comment by ebeshero** [comment]
@Pomilui Need me to reset permissions on the file? Which one is it?

**Comment by ebeshero** [comment]
Just saw—index.html...

**Comment by ebeshero** [comment]
@Pomilui I've just reset the permissions on the Akira web directory so it's open to group writing access--give it a try now!
