### ISSUE TITLE
Akira Canonical Color (for HSV and website palette)

### ISSUE THREAD

**Issue by ebeshero** [Pomilui/Akira_Page#16]
Sites you need for isolating "Akira red" for use on the project site
1) Upload an image and isolate its colors to return values: https://imagecolorpicker.com/en
2) This helps you locate and adjust the HSL factors (see [DHClass-Hub Explanation of HSL](https://github.com/ebeshero/DHClass-Hub/issues/482): 
https://www.w3schools.com/colors/colors_hsl.asp

@Pomilui @MarkTheShark01 @quantum-satire

**Comment by quantum-satire** [comment]
These are the colors and their hex values I used for the site design:
"Akira Red": #ed4630 ![red](https://user-images.githubusercontent.com/28074589/38530839-daf518fc-3c3a-11e8-8127-4ef7cb4431a2.png)
"Akira Teal": #2a6b6f ![teal](https://user-images.githubusercontent.com/28074589/38530844-ddd6810a-3c3a-11e8-84f0-e012741a476a.png)
"Off Black": #161417 ![black](https://user-images.githubusercontent.com/28074589/38530845-df6860e2-3c3a-11e8-8a9d-cfcd9fe2f6ba.png)

These were taken from the advertisements and box art.

I can also help with finding particular colors you need with Photoshop, just let me know :)

**Comment by ebeshero** [comment]
@quantum-satire Ahhh, so you *were* using canonical Akira colors after all! :-) We were exploring HSL() values to make gradients from a red pulled from an Akira poster earlier today--you can see the results at http://newtfire.org:8338/exist/rest/db/npp16/pcsolar-AkiraPowerGraph.svg .

**Comment by ebeshero** [comment]
@quantum-satire Here's some sample code:
```
<rect x="{$currentPersonPos * 5}" y="-{$currentDatePos * 5}" width="5" height="5" fill="hsl(240,{$saturation}%, 50%)"/>
```
The first number in HSL is the hue, and the third is its lightness--those together seem to control what color is displayed. Then you can just vary the saturation factor in the middle. Saturation and Lightness are percentages. We tinkered with it and found that be multiplying the raw count of the characters' exercising their powers in the script multiplied by 10, the gradation started to be visible on the screen. Your results might vary here...I'd start by inputting a meaningfully variant variable, and if it doesn't look right, multiply or divide it by something.

**Comment by quantum-satire** [comment]
@ebeshero I'm wondering if I can implement this into the timeline and other data visualisations on Rick & Morty... Actually, I wonder if we *could* create a heatmap to show off some of the connections Dorothea has in mind in regard to all of the episodes as a grid.

**Comment by ebeshero** [comment]
@quantum-satire You sure could! I've been learning about heat maps from @zme1 and @djbpitt over on [the Toscana project](http://toscana.newtfire.org/html/keyMembers.html).

**Comment by ebeshero** [comment]
@quantum-satire Think of the number of episodes you're representing, and the information you want to sum up visually. You could represent that as a grid, but the blocks don't necessarily have to be super small, and could vary in size and/or color depending on what you want to show! https://www.fusioncharts.com/chart-primers/heat-map-chart/

**Comment by Pomilui** [comment]
@ebeshero Hey, Dr. B

   I'm going to attempt to add the character names, the legend, and the axis labels to the Powers Bar Graph.  Any recommendations?  Thanks.
