### ISSUE TITLE
New Control Scene Network

### ISSUE THREAD

**Issue by Pomilui** [Pomilui/Akira_Page#17]
@ebeshero @MarkTheShark01 @quantum-satire 

Hey, all.  I finished adding all of the control scenes and made a new network graph with the latest commit.   It may need touching up to look good for potentially putting on the back of the DH T-Shirts.  

  Dr. B, please let me know what needs done to pretty up the network.  I used the same settings in "Visualize Parameters" as the first one, but it may look better if done differently.  I separated the characters by faction.  

Node size by Degree ----   
Node color by Avg Shortest Path Length
 Map edge size by EdgeBetweenness   ------    
Map edge color by EdgeBetweenness 

Everyone feel free to play with the network.  While it may not represent who has the most control in the movie, it will suffice for some kind of connection between which characters are involved in control.  Thanks.

 - Nick

**Comment by ebeshero** [comment]
@Pomilui Okay! I think I've got the proof finished for the backs of the T-shirts: 
https://github.com/Pomilui/Akira_Page/blob/master/Cytoscape%20Files/AkiraNet_Transp.png

**Comment by Pomilui** [comment]
@ebeshero Excellent!  The dates on there have a mix of retro and modern times.  Thanks.

**Comment by ebeshero** [comment]
@Pomilui I'm going to ask the class if each of us wants this on the back of a shirt. I imagine you and @MarkTheShark01 and @quantum-satire will want it, but let's make sure...I'd like some help covering the extra expense (=not much, but it adds up!)
