### ISSUE TITLE
Akira Data Page Javascript Help

### ISSUE THREAD

**Issue by Pomilui** [Pomilui/Akira_Page#19]
@quantum-satire 

Hey, Ally.  I'm having trouble changing the background color and font size in the akira.css file.  When the user is viewing the script, the linear gradient background is distracting, and I'd like a better (solid white) background for easier reading.

   I'd also like to implement that Javascript file that highlights control scenes, milestones with powers attributes, and hides/shows the notes I made in the XML describing what's happening in the scene and to hide/show the GIFs of that scene.  

   Any help would be greatly appreciated.  Thanks.

 - Nick

**Comment by quantum-satire** [comment]
Hey Nick!

I went onto the site but I don't see any CSS file associated right now. Are you able to send me the CSS file you have? I'm not sure what you mean by a gradient background. All of the div containers holding text on the site are a solid background, and I don't see the script up yet on the site to see what you mean. Do you have a screenshot?

As far as the JavaScript file, you should just be able to tuck away the association line in the head of the HTML file and push it to the server. Unless you're having trouble with writing that? In which case I'd be more than happy to help out with that too!

**Comment by Pomilui** [comment]
@quantum-satire 

   I haven't been able to upload the updated CSS files to the newtfire server since the lab machines were reset.  The updated CSS files are in the website files here in Akira Page.  There is an HTML file that's called "Akira Script" I believe.  I'm trying to associate it with a different CSS, but I don't think that I have to since I really just need a box to put the entire script body in so that the text isn't set against the gradient GREEN AND BLACK background in the STYLING.CSS.  

   I need to put more work into the Javascript file's functions to make it do what I want it to do, but I'll let you know if I have trouble over the weekend.

**Comment by quantum-satire** [comment]
@Pomilui Okay, I'm working on it now. I'll play with it a bit--also, did you change the font on purpose to Arial or was this a mistake? (I can fix this as well if it was a mistake)

**Comment by Pomilui** [comment]
@quantum-satire 
  
   Thanks, Ally.  Yes, I changed the font to Arial because Mark and I wanted to keep it with a basic font, for now.  Mark will be adding pictures and descriptions to the "Project" page, and I'll be touching up the "About Akira", and Home page.  Have a good weekend!  :1st_place_medal:

**Comment by ebeshero** [comment]
@Pomilui You just need to put your `.ssh` folder back into your lab profile so your keys work again with the newtfire server. It's not anything nearly as difficult as setting it up in the first place. The server just needs to be able to find the .ssh directory.  And you'll need to reset FileZilla settings to find the server.
