### ISSUE TITLE
Need Notes in HTML Script

### ISSUE THREAD

**Issue by Pomilui** [Pomilui/Akira_Page#20]
@ebeshero 

Hey, Dr. B.  

   When going over the Javascript for the Akira Script, I forgot that we didn't add the notes that I'd like to be able to show/hide.  Could I stop by at 3:15 and go over what I need to do in XSLT to do that?  Thanks.

 - Nick

**Comment by ebeshero** [comment]
@Pomilui Sure! I'm here in my office.

**Comment by ebeshero** [comment]
Done!
