### ISSUE TITLE
Need to add web form for Javascript to XSLT

### ISSUE THREAD

**Issue by Pomilui** [Pomilui/Akira_Page#21]
@ebeshero @quantum-satire @MarkTheShark01 @Pomilui

After messing with the XSLT, we forgot to add the web form elements to the XSLT that outputs the Akira Script.html.    The current XSLT processes and outputs note elements, which are prepped in the CSS for Javascript toggling.  However, the current XSLT does not contain the check boxes and whatever else we made today.  That stuff is preserved in an HTML file named in BLOCK CAPS, and we're going to include its web form (checkboxes, etc) in the XSLT so it outputs everything we need.  

 Cheers!

**Comment by ebeshero** [comment]
Done with this commit: https://github.com/Pomilui/Akira_Page/commit/0d6e04125860f3b58a9c1d1f2b8fd28f04fb1630
