### ISSUE TITLE
Splash Page

### ISSUE THREAD

**Issue by quantum-satire** [Pomilui/Akira_Page#6]
Hey all, I put together a splash page for you guys to build from--hopefully this will be inspiring to push ahead with the project! [You can view it here.](http://newtfire.org/akira/)

Feel free to use it or trash it for your own design. I can walk you through how I created it during the next meeting so you can edit and add to it if you wish.

**Comment by quantum-satire** [comment]
![screen shot 2018-02-23 at 11 20 36 pm](https://user-images.githubusercontent.com/28074589/36625595-90833c80-18f0-11e8-8c23-9f0e7610ea6e.png)
Made an alternate version... more 80s. (I love 80s design, couldn't help going overboard...)

**Comment by Pomilui** [comment]
@quantum-satire @MarkTheShark01   Wow!  Both look great.  Thanks!

**Comment by ajnewton1** [comment]
That looks fantastic @quantum-satire

**Comment by quantum-satire** [comment]
Thanks @ajnewton1 !

**Comment by quantum-satire** [comment]
@Pomilui Let me know if I can do anything to help put that on the site! It can be tricky to play around with the CSS and HTML the first go-around.
